---
node_exporter_version: '1.2.2'
node_exporter_user: 'node_exporter'
node_exporter_group: 'node_exporter'
node_exporter_install_dir: '/usr/local/bin'
node_exporter_web_listen_address: '0.0.0.0:9100'
