---
- name: Install Node Exporter
  ansible.builtin.yum:
    name: node_exporter
    state: present

- name: Add Node Exporter service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - Restart Node Exporter

- name: Ensure Node Exporter is running
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
