---
- name: Install Prometheus
  ansible.builtin.yum:
    name: prometheus
    state: present

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
  notify:
    - Reload Prometheus

- name: Add Prometheus service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - Restart Prometheus

- name: Ensure Prometheus is running
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
