---
- name: Install FluentBit
  ansible.builtin.yum:
    name: fluentbit
    state: present

- name: Configure FluentBit
  ansible.builtin.template:
    src: fluentbit.conf.j2
    dest: /etc/fluentbit/fluentbit.conf
  notify:
    - Restart FluentBit

- name: Start FluentBit
  ansible.builtin.systemd:
    name: fluentbit
    state: started
    enabled: yes
